name: 'test-gnome-flatpak-app-action'
description: 'Test GNOME Flatpak apps'

inputs:
  manifest:
    description: 'Path to Flatpak manifest'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run
      env:
        MANIFEST: ${{ inputs.manifest }}
      shell: bash
      run: |
        /entrypoint.sh
